export const countries = [
    { name: 'United States', code: '+1', iso: 'US' },
    { name: 'Canada', code: '+1', iso: 'CA' },
    { name: 'United Kingdom', code: '+44', iso: 'GB' },
    { name: 'Australia', code: '+61', iso: 'AU' },
    { name: 'India', code: '+91', iso: 'IN' },
    { name: 'Germany', code: '+49', iso: 'DE' },
    { name: 'France', code: '+33', iso: 'FR' },
    { name: 'Japan', code: '+81', iso: 'JP' },
    { name: 'China', code: '+86', iso: 'CN' },
    { name: 'Brazil', code: '+55', iso: 'BR' },
    { name: 'Mexico', code: '+52', iso: 'MX' },
    { name: 'South Africa', code: '+27', iso: 'ZA' },
    { name: 'Nigeria', code: '+234', iso: 'NG' },
    { name: 'Egypt', code: '+20', iso: 'EG' },
    { name: 'Indonesia', code: '+62', iso: 'ID' },
    { name: 'Pakistan', code: '+92', iso: 'PK' },
    { name: 'Bangladesh', code: '+880', iso: 'BD' },
    { name: 'Russia', code: '+7', iso: 'RU' },
    { name: 'Spain', code: '+34', iso: 'ES' },
    { name: 'Italy', code: '+39', iso: 'IT' },
    { name: 'Argentina', code: '+54', iso: 'AR' },
    { name: 'Colombia', code: '+57', iso: 'CO' },
    { name: 'Kenya', code: '+254', iso: 'KE' },
    { name: 'Philippines', code: '+63', iso: 'PH' },
    { name: 'Saudi Arabia', code: '+966', iso: 'SA' }
  ];